# .github/workflows/update_data.yml

name: Update Data and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 当 main 分支有更新时触发
  workflow_dispatch: # 允许手动触发

# 关键修复：为工作流授予向 gh-pages 分支写入内容的权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Python script to update data
        run: |
          # 如果有依赖，可以在这里安装
          # pip install -r requirements.txt
          python update_data.py # 假设此脚本会生成或更新 ./data/news_data.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 核心修复：将发布目录从 './data' 改为 './'
          # 这会发布仓库中的所有文件 (index.html, main.css, scripts.js, 和 data/ 目录)
          # 而不是仅仅发布 data 目录。
          publish_dir: ./
          # keep_files: false 保持不变是好的实践，它确保了每次部署都是一个干净的状态。
          # 因为现在 publish_dir 正确了，所以它会先清空，然后上传所有正确的文件。
          keep_files: false
