name: Deploy Website to GH Pages

on:
  # 当推送到 main 分支时自动触发
  push:
    branches:
      - main
  
  # 允许在 Actions 页面手动触发此工作流程
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          # GITHUB_TOKEN 是由 GitHub 自动提供的，无需手动设置
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # 核心修复：指定仓库根目录 (`./`) 作为发布内容的来源
          # 这将确保 index.html, scripts/, data/ 等所有文件都被正确部署
          publish_dir: ./
          
          # 指定部署目标分支为 gh-pages
          publish_branch: gh-pages
          
          # 推荐选项：每次都创建一个全新的、无历史记录的分支，保持部署分支的整洁
          force_orphan: true
