# .github/workflows/update_data.yml

name: Update News Data Automatically

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 定义定时任务，使用Cron表达式
    # 此处设置为每30分钟执行一次
    - cron: '*/30 * * * *'

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    steps:
      # 步骤1: 检出（Checkout）你的代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤2: 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 指定Python版本

      # 步骤3: 安装Python依赖库 (如果需要)
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install requests beautifulsoup4 # 如果你的脚本中用到了这些库

      # 步骤4: 运行数据更新脚本
      - name: Run update script
        run: python update_data.py

      # 步骤5: 自动提交并推送更新后的 data/news_data.json 文件
      - name: Commit and push if files changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Automatic data update"
          file_pattern: data/news_data.json # 只提交此文件的变更
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
