# .github/workflows/update_data.yml

name: Build and Deploy News Dashboard

on:
  # 每天UTC时间0点（北京时间上午8点）自动运行一次
  schedule:
    - cron: '0 0 * * *'
  
  # 允许在 Actions 页面手动触发此工作流程
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build Data & Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script to generate news data
        # 关键步骤：运行Python脚本。API密钥通过环境变量安全地传递给脚本。
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python update_data.py

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          # GITHUB_TOKEN 是由 GitHub 自动提供的，无需手动设置
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # 核心修复：指定仓库根目录 (`./`) 作为发布内容的来源
          # 这将确保 index.html, scripts/, 以及新生成的 data/ 都被正确部署
          publish_dir: ./
          
          # 指定部署目标分支为 gh-pages
          publish_branch: gh-pages
          
          # 推荐选项：每次都创建一个全新的、无历史记录的分支，保持部署分支的整洁
          force_orphan: true
